# Generated by Django 5.2.4 on 2026-08-08 00:27

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "school",
                    models.CharField(default="", max_length=100, verbose_name="学校"),
                ),
                (
                    "grade",
                    models.CharField(default="", max_length=100, verbose_name="年级"),
                ),
                (
                    "birth_year",
                    models.IntegerField(default=2006, verbose_name="出生年份"),
                ),
                ("intro", models.JSONField(default=list, verbose_name="简介段落")),
                ("directions", models.JSONField(default=list, verbose_name="学习方向")),
                ("interests", models.JSONField(default=list, verbose_name="兴趣爱好")),
                (
                    "stats",
                    models.JSONField(
                        default=list, verbose_name="一些数据 [{label,value}]"
                    ),
                ),
                (
                    "contact",
                    models.JSONField(
                        default=dict, verbose_name="联系方式 {email,github,location}"
                    ),
                ),
                (
                    "blog_purpose",
                    models.JSONField(default=list, verbose_name="博客初衷段落"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=200, unique=True, verbose_name="标识"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                ("date", models.DateField(verbose_name="日期")),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                ("excerpt", models.TextField(verbose_name="摘要")),
                (
                    "content",
                    markdownx.models.MarkdownxField(verbose_name="正文 Markdown"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "comments",
                    models.JSONField(default=list, verbose_name="评论（预留）"),
                ),
            ],
            options={
                "ordering": ["-date", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=200, unique=True, verbose_name="标识"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "emoji",
                    models.CharField(default="", max_length=16, verbose_name="Emoji"),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="", max_length=300, verbose_name="一句话简介"
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="详细描述")),
                ("tech", models.JSONField(default=list, verbose_name="技术栈")),
                (
                    "status",
                    models.CharField(default="", max_length=20, verbose_name="状态"),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "url",
                    models.URLField(blank=True, default="", verbose_name="Demo 链接"),
                ),
                (
                    "github",
                    models.URLField(blank=True, default="", verbose_name="GitHub 链接"),
                ),
                ("related", models.JSONField(default=list, verbose_name="相关项目")),
            ],
            options={
                "ordering": ["-date", "slug"],
            },
        ),
    ]
