# Generated by Django 5.2.4 on 2026-08-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_comment_parent_notification_passwordresetcode"),
    ]

    operations = [
        # 评论数改为实时从 Comment 表统计，删除从 md frontmatter 导入的假 comments JSONField
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
    ]
