# Generated by Django 5.2.4 on 2026-08-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_remove_post_comments"),
    ]

    operations = [
        # 「一些数据」改为实时统计（项目/文章/代码提交数），删除写死的假 stats JSONField
        migrations.RemoveField(
            model_name="about",
            name="stats",
        ),
    ]
