# Generated by Django 5.2.4 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_about_stats"),
    ]

    operations = [
        # 吊牌三图改为后台可上传（绳索贴图 / 卡片正面 / 卡片反面），留空时前端用内置默认
        migrations.AddField(
            model_name="about",
            name="lanyard_image",
            field=models.ImageField(blank=True, upload_to="lanyard/", verbose_name="绳索贴图"),
        ),
        migrations.AddField(
            model_name="about",
            name="card_front_image",
            field=models.ImageField(blank=True, upload_to="lanyard/", verbose_name="卡片正面图"),
        ),
        migrations.AddField(
            model_name="about",
            name="card_back_image",
            field=models.ImageField(blank=True, upload_to="lanyard/", verbose_name="卡片反面图"),
        ),
    ]
