# Generated by Django 5.2.4 on 2026-08-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_about_lanyard_images"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 首页欢迎语/副标题后台化（留空走前端默认）
        migrations.AddField(
            model_name="about",
            name="home_welcome",
            field=models.CharField(blank=True, max_length=100, verbose_name="首页欢迎语"),
        ),
        migrations.AddField(
            model_name="about",
            name="home_tagline",
            field=models.CharField(blank=True, max_length=200, verbose_name="首页副标题"),
        ),
        # 用户扩展资料（头像，自主上传）
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/", verbose_name="头像")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
