# Generated by Django 5.2.4 on 2026-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_about_home_text_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, max_length=200, verbose_name="个性签名"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(
                default=False, verbose_name="邮箱已验证（预留接口，暂未启用）"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_muted_forever",
            field=models.BooleanField(default=False, verbose_name="永久禁言"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="muted_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="禁言截止"),
        ),
        migrations.CreateModel(
            name="RateLimitHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=45, verbose_name="IP")),
                ("action", models.CharField(max_length=20, verbose_name="动作")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ip", "action", "created_at"],
                        name="content_rat_ip_3aa062_idx",
                    )
                ],
            },
        ),
    ]
